/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentPanel: typeof import('./components/AgentPanel.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/AppTopbar.vue')['default']
    BuildStageProgress: typeof import('./components/BuildStageProgress.vue')['default']
    ExampleHelp: typeof import('./components/ExampleHelp.vue')['default']
    FileBrowser: typeof import('./components/FileBrowser.vue')['default']
    ImageViewer: typeof import('./components/ImageViewer.vue')['default']
    LocalePicker: typeof import('./components/LocalePicker.vue')['default']
    LocaleSelectTabs: typeof import('./components/LocaleSelectTabs.vue')['default']
    PageLoading: typeof import('./components/PageLoading.vue')['default']
    RightRail: typeof import('./components/RightRail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TaskLogPanel: typeof import('./components/TaskLogPanel.vue')['default']
    TaskRunBar: typeof import('./components/TaskRunBar.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCheckboxGroup: typeof import('tdesign-vue-next')['CheckboxGroup']
    TCollapse: typeof import('tdesign-vue-next')['Collapse']
    TCollapsePanel: typeof import('tdesign-vue-next')['CollapsePanel']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TStatistic: typeof import('tdesign-vue-next')['Statistic']
    TStepItem: typeof import('tdesign-vue-next')['StepItem']
    TSteps: typeof import('tdesign-vue-next')['Steps']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}
