/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentPanel: typeof import('./components/AgentPanel.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/AppTopbar.vue')['default']
    BuildStageProgress: typeof import('./components/BuildStageProgress.vue')['default']
    ExampleHelp: typeof import('./components/ExampleHelp.vue')['default']
    FileBrowser: typeof import('./components/FileBrowser.vue')['default']
    ImageViewer: typeof import('./components/ImageViewer.vue')['default']
    PageLoading: typeof import('./components/PageLoading.vue')['default']
    RightRail: typeof import('./components/RightRail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TaskLogPanel: typeof import('./components/TaskLogPanel.vue')['default']
    TaskRunBar: typeof import('./components/TaskRunBar.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCollapse: typeof import('tdesign-vue-next')['Collapse']
    TCollapsePanel: typeof import('tdesign-vue-next')['CollapsePanel']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
  }
}
